### ISSUE TITLE
Crash on non titled chat

### ISSUE THREAD

**Issue by Coriana** [mohamed-chs/chatgpt-history-export-to-md#15]
**Describe the bug**
When there is no title, the script crashes.

TLDK:
fix is check if none, if none add title.:
src\utils.py
def sanitize_title(title: str) -> str:
    """Sanitize the title by replacing disallowed characters with '-'.

    Args:
        title (str): The title to sanitize.

    Returns:
        str: The sanitized title.
    """
    if title is None:
        title = "Untitled"  # or any other default value

    sanitized_title: str = DISALLOWED_CHARS_PATTERN.sub("-", title.strip())
    return sanitized_title

**Comment by pjamar** [comment]
Probably making them "Untitled" will provoke collisions if there is more than one. I'd suggest on `main.py` use the creation timestamp. Something like:
```python
if not conversation["title"]:
   title: str = datetime.fromtimestamp(conversation["create_time"]).strftime('%Y-%m-%d %H:%M:%S')
else:
   # Use title
```

**Comment by mohamed-chs** [comment]
Thanks for bringing this up. It's weird, I thought I had in many places handled the empty title case, ...
I added replaced all `["title"]`s with `.get("title", "Untitled")`. Let me know if you still have the issue.
As for the title duplication, I just add a "(#occurence-1)" after the title, so that shouldn't be a problem.
Thanks again !

**Comment by Coriana** [comment]
Thank you.
Sorry I didn't do a proper bug report, I was walking out the door, and had merely fixed the issue on my end, and wasn't prepared to actually write up a full report of how to replicate, as I didn't have enough time to start loading files and looking for the chat in question. :-/

Awesome project, exactly what I was looking for regarding my exports of chatgpt over time.
