### ISSUE TITLE
python main.py causes error in  configs_dict = get_user_configs()

### ISSUE THREAD

**Issue by DcsPeterDickten** [mohamed-chs/chatgpt-history-export-to-md#23]
**Describe the bug**
I use the step-by-step instructions from https://github.com/mohamed-chs/chatgpt-history-export-to-md

**To Reproduce**
1. git clone https://github.com/mohamed-chs/chatgpt-history-export-to-md.git
2. cd chatgpt-history-export-to-md
3. python setup.py
4. source .venv/bin/activate
5. python main.py

(same result when using python3)

**Expected behavior**
The application should ask where the downloaded data is (or ?)

**Output**

Traceback (most recent call last):
  File "/Users/MYUSERNAME/temp/chatgpt-history-export-to-md/main.py", line 122, in <module>
    main()
  File "/Users/MYUSERNAME/temp/chatgpt-history-export-to-md/main.py", line 38, in main
    configs_dict = get_user_configs()
                   ^^^^^^^^^^^^^^^^^^
  File "/Users/MYUSERNAME/temp/chatgpt-history-export-to-md/controllers/configuration.py", line 22, in get_user_configs
    default_configs["zip_file"] = get_openai_zip_filepath()
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/MYUSERNAME/temp/chatgpt-history-export-to-md/utils/utils.py", line 93, in get_openai_zip_filepath
    default_zip_filepath: Path = max(zip_files, key=lambda x: x.stat().st_ctime)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence

**OS**
 - OS: macOS 14.0
- Python 3.11.6

**Additional context**

**Comment by mohamed-chs** [comment]
Thanks for pointing that out!
It should ideally pick the most recent ZIP file download in ~/Downloads, and that should be the default input value, that you can change. But without any zip in Downloads, the default input is None and that where it crashes. I think I'll set that default behavior to be an empty input string.
Let me know if you're still having issues.
